# Generated by Django 5.1.6 on 2025-03-27 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='time_elapsed',
            field=models.CharField(max_length=20),
        ),
    ]
